### ISSUE TITLE
ChatGPT Discord bot functions

### ISSUE THREAD

**Issue by TRexAILab** [Zero6992/Zero6992#10]
Hi! Please tell me how to set a limit on calls from the user(s) to the bot? How do I set the ability to call a bot to users with a certain role? P.s. you have a great application, thank you so much for doing this!

**Comment by khuukhoidanh** [comment]
![Screenshot_1](https://github.com/Zero6992/Zero6992/assets/150052729/c91358ac-8813-49a5-9dd7-68cbd5900222)
Can you help me this one <33
