### ISSUE TITLE
a new app using chatGPT API

### ISSUE THREAD

**Issue by Jiwanczuk** [Zero6992/Zero6992#2]
Hey there, I would like to know if you are available to work on new projects. Im interested in building a new app using the reversed engineered chat GPT API.

**Comment by Zero6992** [comment]
> Hey there, I would like to know if you are available to work on new projects. Im interested in building a new app using the reversed engineered chat GPT API.

I think using a reverse engineered ChatGPT API would make the service unstable, and for making an app I feel that using the official API may be a better option
