### ISSUE TITLE
Issue with chatGPT - Discord bot

### ISSUE THREAD

**Issue by Vovchanok** [Zero6992/Zero6992#4]
Hello.
Please look. 
I faced with error: ImportError: cannot import name 'AppCommandOptionType' from 'discord.enums'
<img width="836" alt="Снимок экрана 2023-02-21 в 7 14 19 PM" src="https://user-images.githubusercontent.com/113111637/220399658-af6708cf-1aa2-4cc8-8dcb-1e6374c0698f.png">

Then I applied your recommendation and removed "from discord import app_commands" in bot.py

After this I got another error: NameError: name 'app_commands' is not defined #in bot.py 16 line
<img width="831" alt="Снимок экрана 2023-02-21 в 7 18 44 PM" src="https://user-images.githubusercontent.com/113111637/220400712-e871a543-9920-4b2c-b1b2-7b04fdc8bb6d.png">

Please, suggest.
Thank you.

Discord 2.1.0
Python 3.11
I use macOS 13.1

**Comment by Vovchanok** [comment]
I also tried to put "from discord.ext import commands" into bot.py. No positive results.

**Comment by Zero6992** [comment]
Consider using Python 3.9 version
