### ISSUE TITLE
Editing prompts of the bot

### ISSUE THREAD

**Issue by xn4k** [Zero6992/Zero6992#5]
I am not really skilled in Python, i really appreciate you version of the bot and i had a question about it.

What i want:
For example I want the bot to behave in a role of Batman. So every time after i am writing /chat, i am starting like that: /chat Behave and answer like batman and tell me "then putting my message here". 

So how and where i can edit the message variable so i don't have to write "Behave and answer like batman and tell me..." all the time before starting my prompt?

I tried it like that in bot.py:

`async def send_message(message, user_message):
    await message.response.defer(ephemeral=isPrivate)
    try:
        response = '> **' + 'Behave and answer like batman and tell me...' + user_message + '** - <@' + \
            str(message.user.id) + '>\n\n'
        response = f"{response}{user_message}{await responses.handle_response(user_message)}"
`
But it of course dont working, so maybe you can help me how i can do it?
Appreciate you answer!

**Comment by Zero6992** [comment]
you can edit `starting-prompt.txt` and give some prepend  prompt in it

**Comment by xn4k** [comment]
I tried it already but its only does it once while starting, all the other time it dont remember me telling the bot act in some way , so i was searching for a way to correct some message-prompt variable
