### ISSUE TITLE
ChatGPT Bot Discord Help

### ISSUE THREAD

**Issue by UnPapiChulo** [Zero6992/Zero6992#7]
Hey @Zero6992 

Is there any way you could help me modify the code, or let me know how (im really new at this) to make it so the responses (when using "/chat") from the Bot on my discord channel appear as embedded messages? (preferably in the color red)

Thanks in Advance!

**Comment by khuukhoidanh** [comment]
![Screenshot_1](https://github.com/Zero6992/Zero6992/assets/150052729/530f16ef-f313-4b68-8057-dc8f81c7f282)
Can you help me with this one pls thks youu

**Comment by Zero6992** [comment]
Breaking change, please go see README
